DROP TABLE APPS.KTC_CA002_LOAD_CARD_TEMP CASCADE CONSTRAINTS;

CREATE TABLE APPS.KTC_CA002_LOAD_CARD_TEMP
(
  TRANSACTION_ID    NUMBER,
  JE_BATCH_ID       NUMBER,
  JE_HEADER_ID      NUMBER,
  JE_LINE_NUM       NUMBER,
  REQUEST_ID        NUMBER,
  FILE_ID           NUMBER,
  FILE_NAME         VARCHAR2(1000 BYTE),
  BATCH_NAME        VARCHAR2(1000 BYTE),
  JOURNAL_NAME      VARCHAR2(500 BYTE),
  CATEGORY_NAME     VARCHAR2(200 BYTE),
  GL_DATE           DATE,
  JOURNAL_DESC      VARCHAR2(1000 BYTE),
  CURRENCY_CODE     CHAR(10 BYTE),
  JOURNAL_LINE      NUMBER,
  COMPANY           VARCHAR2(10 BYTE),
  RC                VARCHAR2(10 BYTE),
  BASEL             VARCHAR2(10 BYTE),
  ACCOUNT           VARCHAR2(10 BYTE),
  PRODUCT           VARCHAR2(10 BYTE),
  INTERCOMPANY      VARCHAR2(10 BYTE),
  TAX_CODE          VARCHAR2(10 BYTE),
  RESERVE           VARCHAR2(10 BYTE),
  ALLOCATION        VARCHAR2(10 BYTE),
  ENTERED_DR        NUMBER,
  ENTERED_CR        NUMBER,
  REFERENCE_NO      VARCHAR2(200 BYTE),
  STATEMENT_NO      VARCHAR2(200 BYTE),
  LINE_DESC         VARCHAR2(1000 BYTE),
  VOUCHER_NO_OUT    VARCHAR2(100 BYTE),
  LINE_NO_OUT       NUMBER,
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER,
  USER_LOGIN_ID     NUMBER,
  ERROR_FLAG        CHAR(1 BYTE),
  ERROR_MESSAGE     VARCHAR2(3000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER APPS.KTC_CA002_LOAD_CARD_TEMP_TRG
   BEFORE INSERT OR UPDATE
   ON APPS.KTC_CA002_LOAD_CARD_TEMP
   FOR EACH ROW
BEGIN
   IF UPDATING
   THEN
      :NEW.LAST_UPDATE_DATE := SYSDATE;
   END IF;

   IF INSERTING
   THEN
      :NEW.TRANSACTION_ID := KTC_CA002_LOAD_CARD_TEMP_S.NEXTVAL;
      :NEW.LAST_UPDATE_DATE := SYSDATE;
      :NEW.CREATION_DATE := SYSDATE;
   END IF;
END;
/